from decimal import Decimal

from pymodbus.client import ModbusSerialClient

class Em511:
    def __init__(self, device_address: int, client: ModbusSerialClient) -> None: ...
    V: Decimal
    A: Decimal
    password: int

    def _unpack(self, registers: list[int], address: int) -> int: ...
    def _write_register(self, address: int, value: int) -> None: ...
    def _read_register(self, register_name: str) -> Decimal | int: ...
    def _read_input_registers(self, address: int, count: int) -> list[int]: ...
