name: DCO
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Install dco-check using uv
        run: |
          uv tool install dco-check --upgrade

      - name: Check DCO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dco-check --verbose --exclude-pattern 'dependabot\[bot\]@users\.noreply\.github\.com'
